# Generated by Django 5.0.1 on 2024-04-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_missingperson_liked_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
